language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amiroous/docker-k8s-app -f Dockerfile.dev .

script:
  - docker run -e CI=true amiroous/docker-k8s-app npm run test
