language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amiroous/docker-k8s-app -f Dockerfile.dev .

script:
  - docker run -e CI=true amiroous/docker-k8s-app npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-k8s-app"
  env: "DockerK8sApp-env"
  bucket_name: "elasticbeanstalk-us-west-1-627871014836" # AWS S3
  bucket_path: "docker-k8s-app" # Same as App
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"